### ISSUE TITLE
Error: Cannot find module '../model'

### ISSUE THREAD

**Issue by jeebee2013** [Mangopay/mangopay2-nodejs-sdk#16]
Hi 
on ubuntu 14.04.3 LTS 
when running, for example a getuser
i got the following error 
Error: Cannot find module '../model'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/bitnami/nodejs/lib/node_modules/mangopay2-nodejs-sdk/lib/models/CardPreAuthorization.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

model npm is installed...

Same script running on my mac desktop works like a charm..
any  idea?
thanks

**Comment by lupugabriel1** [comment]
I am researching this problem. Thanks for bringing it up ! Will keep you posted !

**Comment by lupugabriel1** [comment]
@jeebee2013 thank you again for bringing up this issue. The bug was very silly - apparently ubuntu does like case sensitive require paths ( which makes a lot of sense after all ). Fix was applied and version was bumped to v1.0.1 . Feel free to check it out and provide feedback if you can. Thanks !

**Comment by jeebee2013** [comment]
fixed! 
thanks!
