### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir '/services'

### ISSUE THREAD

**Issue by cbarlow1993** [Mangopay/mangopay2-nodejs-sdk#165]
Trying to use this SDK but get an error. Not sure what other information you will find useful for debugging but happy to provide anything extra.

```
Error: ENOENT: no such file or directory, scandir '/services'
    at Object.readdirSync (fs.js:779:3)
    at Api._servicesLoader (/backend/services/stores/.webpack/service/webpack:/backend/node_modules/mangopay2-nodejs-sdk/lib/api.js:311:1)
    at new Api (/backend/services/stores/.webpack/service/webpack:/backend/node_modules/mangopay2-nodejs-sdk/lib/api.js:62:1)
    at create (/backend/services/stores/.webpack/service/webpack:/backend/services/stores/stores.js:143:21)
```

```
import mangopay from 'mangopay2-nodejs-sdk';

var mangoApi = new mangopay({
    clientId: '...',
    clientApiKey: '...',
    debugMode: true
});
```

Node: v12.3.1
 package.json: "mangopay2-nodejs-sdk": "^1.10.0",

**Comment by cbarlow1993** [comment]
Just read a bit further and it's the same issue as https://github.com/Mangopay/mangopay2-nodejs-sdk/issues/121.

Support with Webpack would be greatly appreciated as this is currently unusable.
