### ISSUE TITLE
Typescript payouts object does not allow PaymentType

### ISSUE THREAD

**Issue by williamdes** [Mangopay/mangopay2-nodejs-sdk#205]
## Error and trace

```
Create Payout needs MeanOfPaymentDetails or PaymentType undefined
(node:1502494) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bind' of undefined
    at /mnt/Dev/[redacted]/node_modules/mangopay2-nodejs-sdk/lib/api.js:165:51
    at tryCallTwo (/mnt/Dev/[redacted]/node_modules/promise/lib/core.js:45:5)
    at doResolve (/mnt/Dev/[redacted]/node_modules/promise/lib/core.js:200:13)
    at new Promise (/mnt/Dev/[redacted]/node_modules/promise/lib/core.js:66:3)
    at Api._requestApi (/mnt/Dev/[redacted]/node_modules/mangopay2-nodejs-sdk/lib/api.js:158:14)
    at Api.method (/mnt/Dev/[redacted]/node_modules/mangopay2-nodejs-sdk/lib/api.js:152:21)
    at child.create (/mnt/Dev/[redacted]/node_modules/mangopay2-nodejs-sdk/lib/services/PayOuts.js:28:26)
    at MangopayService.payout (/mnt/Dev/[redacted]/dist/src/payment/mangopay/mangopay.service.js:209:72)
```

## Implementation

```ts
        const payoutToCreate: MangoPay.PayOut.CreatePayOut = {
            AuthorId: payoutData.authorId,
            DebitedFunds: {
                Currency: 'EUR',
                Amount: payoutData.debitedAmount,
            },
            Fees: {
                Currency: 'EUR',
                Amount: payoutData.debitedFeesAmount,
            },
            BankAccountId: payoutData.bankAccountId,
            DebitedWalletId: payoutData.debitedWalletId,
            BankWireRef: payoutData.bankWireRef,
            Tag: payoutData.tag,
            PaymentType: 'BANKWIRE',
        };
```

## Hack
```diff
- const payoutToCreate: MangoPay.PayOut.CreatePayOut = {
+ const payoutToCreate: any = {
```

## IDE / TS error

```
Type '{ AuthorId: string; DebitedFunds: { Currency: "EUR"; Amount: number; }; Fees: { Currency: "EUR"; Amount: number; }; BankAccountId: string; DebitedWalletId: string; BankWireRef: string; Tag: string; PaymentType: string; }' is not assignable to type 'CreatePayOut'.
  Object literal may only specify known properties, and 'PaymentType' does not exist in type 'CreatePayOut'.ts(2322)
```

**Comment by mangomaxoasis** [comment]
Hi @williamdes 
We're looking into it

**Comment by mangomaxoasis** [comment]
fixed merged, will be in next release 
Max

**Comment by williamdes** [comment]
> fixed merged, will be in next release
> Max

Thanks you Max
Closed by https://github.com/Mangopay/mangopay2-nodejs-sdk/pull/206
