### ISSUE TITLE
Mocking issue

### ISSUE THREAD

**Issue by soullivaneuh** [Mangopay/mangopay2-nodejs-sdk#219]
In order to increase my test coverage for the mangopay2 SDK usage, I created a mock of it.

I started by a very simple implementation of the user creation:

```typescript
// __mocks__/mangopay2-nodejs-sdk.ts
import { default as BaseMangoPay } from 'mangopay2-nodejs-sdk';

class Users extends BaseMangoPay.Users {
  create: BaseMangoPay.Users['create'] = (data) => {
    return new Promise((resolve) => resolve({
      Id: '1337',
    }));
  }
}

export default class MangoPay extends BaseMangoPay {
  Users: Users
}
```

I have two issues here.

First, typescript is yelling on the `Users.create` method with the following error:

```
Type '(data: any) => Promise<unknown>' is not assignable to type 'MethodOverload<CreateUserLegalData, UserLegalData> & MethodOverload<CreateUserNaturalData, UserNaturalData>'.
  Type '(data: any) => Promise<unknown>' is not assignable to type 'MethodOverload<CreateUserLegalData, UserLegalData>'.
    Type 'Promise<unknown>' is not assignable to type 'Promise<WithResponse<UserLegalData>>'.
      Type '{}' is missing the following properties from type 'WithResponse<UserLegalData>': statusCode, body, headers
```

I am quite surprised I have to define the method paremeters and return typing as I already specified which typing to use for this override (`BaseMangoPay.Users['create']`).

Secondly, my tests are not working with the following error on each one:

```
    TypeError: Class extends value undefined is not a constructor or null

      1 | import { default as BaseMangoPay } from 'mangopay2-nodejs-sdk';
      2 | 
    > 3 | class Users extends BaseMangoPay.Users {
        |                                  ^
      4 |   create: BaseMangoPay.Users['create'] = (data) => {
      5 |     return new Promise((resolve) => resolve({
      6 |       Id: '1337',

      at Object.<anonymous> (__mocks__/mangopay2-nodejs-sdk.ts:3:34)
      at Object.<anonymous> (src/mango.ts:1245:41)
```

I am quite confused here. How should I manage mocking for that SDK?

Thanks

**Comment by soullivaneuh** [comment]
I finally managed to make the mock working with a correct implementation of the class:

```typescript
import { default as BaseMangoPay } from 'mangopay2-nodejs-sdk';

export default class MangoPay extends BaseMangoPay {
  constructor(config) {
    super(config);
    this.Users = {
      create: (data) => {
        return new Promise((resolve) => resolve({
          ...data,
          Id: '421337',
        }));
      }
    }
  }
}
```

However, I still have the typescript typing issue on the `Users.create` method:

```
Type '(data: any) => Promise<unknown>' is not assignable to type 'MethodOverload<CreateUserLegalData, UserLegalData> & MethodOverload<CreateUserNaturalData, UserNaturalData>'.
  Type '(data: any) => Promise<unknown>' is not assignable to type 'MethodOverload<CreateUserLegalData, UserLegalData>'.
    Type 'Promise<unknown>' is not assignable to type 'Promise<WithResponse<UserLegalData>>'.
      Type '{}' is missing the following properties from type 'WithResponse<UserLegalData>': statusCode, body, headersts(2322)
index.d.ts(3494, 5): The expected type comes from property 'create' which is declared here on type 'Users'
```

**Comment by mangomaxoasis** [comment]
Hi @soullivaneuh 
We're looking into it

**Comment by SoloJr** [comment]
Hi @soullivaneuh 

You should try to mock the creation of a LEGAL or NATURAL user. Using just user it won't work. 

Mircea
