### ISSUE TITLE
Impossible to add card with api on deployed on server

### ISSUE THREAD

**Issue by dhulqarnayn** [Mangopay/mangopay2-nodejs-sdk#300]
Hi,

I have a problem when adding a credit card. Everything works very well locally.
But after deploying in "staging" on my server, it no longer works. However, there is no problem when creating a user and a wallet.

**Here is my code:**

```
mangoPayApi.CardRegistrations.create({
    UserId: mangopayId,
    Currency: "EUR",
    CardType: "CB_VISA_MASTERCARD",
  })
    .then((cardRegistrationData) => {
      var cardData = {
        cardNumber: card.number,
        cardExpirationDate: card.expirationDate,
        cardCvx: card.cvx,
      };

      var headers = {
        "Content-Type": "application/x-www-form-urlencoded",
      };

      var options = {
        url: cardRegistrationData.CardRegistrationURL,
        headers: headers,
        form: {
          data: cardRegistrationData.PreregistrationData,
          accessKeyRef: cardRegistrationData.AccessKey,
          cardNumber: cardData.cardNumber,
          cardExpirationDate: cardData.cardExpirationDate,
          cardCvx: cardData.cardCvx,
        },
      };
      console.log("options");
      console.log(options);
      request.post(options, (err, httpResponse, body) => {
        console.log("body");
        console.log(body);
        cardRegistrationData.RegistrationData = body;
        console.log("cardRegistrationData");
        console.log(cardRegistrationData);
        mangoPayApi.CardRegistrations.update(
          cardRegistrationData,
          async (data) => {
            if (data.Status === "ERROR") {
              res.status(400).json({
                error: data,
                message:
                  "Une erreur s'est produite lors de l'ajout de votre carte bleue",
              });
            } else {
              ...
            }
          }
        );
      });
    })
    .catch((err) => {
      res.status(400).json({
        message: err.message,
      });
    });
```

**Here is the local result:**

```
options
{
  url: 'https://homologation-webpayment.payline.com/webpayment/getToken',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  form: {
    data: '-3qr8M0QBM0xs1g25H_bHr55-WF91NPhiyiBrQyd--OaX8jkwm8ghfTC10XnYam_2ddFLVXdicolcUIkv_kKEA',
    accessKeyRef: '1X0m87dmM2LiwFgxPLBJ',
    cardNumber: '4970104100876596',
    cardExpirationDate: '1022',
    cardCvx: '123'
  }
}

body
data=dAj315t4g0Sq0Zy7Th16scu05s54i1vW32r99D6mbTq1b77QqjvT9EHsNoG6v6cwMrVOOZqxLNZHutyL-N3OzMn1qD7TzmrIJFI7wRXBzDj8j6o-48ddpgsS2pXzLc-4Nx0xgKTVnyDj15oG8jR88g

cardRegistrationData
child {
  Id: '127669440',
  Tag: null,
  CreationDate: 1639697333,
  UserId: '127664013',
  AccessKey: '1X0m87dmM2LiwFgxPLBJ',
  PreregistrationData: '-3qr8M0QBM0xs1g25H_bHr55-WF91NPhiyiBrQyd--OaX8jkwm8ghfTC10XnYam_2ddFLVXdicolcUIkv_kKEA',
  RegistrationData: 'data=dAj315t4g0Sq0Zy7Th16scu05s54i1vW32r99D6mbTq1b77QqjvT9EHsNoG6v6cwMrVOOZqxLNZHutyL-N3OzMn1qD7TzmrIJFI7wRXBzDj8j6o-48ddpgsS2pXzLc-4Nx0xgKTVnyDj15oG8jR88g',
  CardId: null,
  CardType: 'CB_VISA_MASTERCARD',
  CardRegistrationURL: 'https://homologation-webpayment.payline.com/webpayment/getToken',
  ResultCode: null,
  ResultMessage: null,
  Currency: 'EUR',
  Status: 'CREATED'
}
```

**Here is the result on the API deployed in staging:**

```
options
{
  url: 'https://homologation-webpayment.payline.com/webpayment/getToken',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  form: {
    data: 'Qi7oou23Q8d9B3xUpjdMuWLAHlAiyf-rQSX-R4jkzdjGop4bJPx40Gj_ofx3w5C32ddFLVXdicolcUIkv_kKEA',
    accessKeyRef: '1X0m87dmM2LiwFgxPLBJ',
    cardNumber: '4970104100876596',
    cardExpirationDate: '1022',
    cardCvx: '123'
  }
}

body
undefined

cardRegistrationData
child {
  Id: '127669452',
  Tag: null,
  CreationDate: 1639697358,
  UserId: '127322537',
  AccessKey: '1X0m87dmM2LiwFgxPLBJ',
  PreregistrationData: 'Qi7oou23Q8d9B3xUpjdMuWLAHlAiyf-rQSX-R4jkzdjGop4bJPx40Gj_ofx3w5C32ddFLVXdicolcUIkv_kKEA',
  RegistrationData: undefined,
  CardId: null,
  CardType: 'CB_VISA_MASTERCARD',
  CardRegistrationURL: 'https://homologation-webpayment.payline.com/webpayment/getToken',
  ResultCode: null,
  ResultMessage: null,
  Currency: 'EUR',
  Status: 'CREATED'
}

One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error. {
  Message: 'One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.',
  Type: 'param_error',
  Id: '79806ea6-6249-4a9f-84eb-77e12adca701#1639697490',
  Date: 1639697491,
  errors: { RegistrationData: 'The value  is not valid' }
}
/home/pearl-of-orient/staging/devapi.pearl-of-orient/node_modules/mongoose/lib/document.js:2921
    this.$__.validationError = new ValidationError(this);
                               ^

ValidationError: Card validation failed: mangopayCardId: Path `mangopayCardId` is required.
    at model.Document.invalidate (/home/pearl-of-orient/staging/devapi.pearl-of-orient/node_modules/mongoose/lib/document.js:2921:32)
    at /home/pearl-of-orient/staging/devapi.pearl-of-orient/node_modules/mongoose/lib/document.js:2712:17
    at /home/pearl-of-orient/staging/devapi.pearl-of-orient/node_modules/mongoose/lib/schematype.js:1280:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errors: {
    mangopayCardId: ValidatorError: Path `mangopayCardId` is required.
        at validate (/home/pearl-of-orient/staging/devapi.pearl-of-orient/node_modules/mongoose/lib/schematype.js:1277:13)
        at /home/pearl-of-orient/staging/devapi.pearl-of-orient/node_modules/mongoose/lib/schematype.js:1260:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (/home/pearl-of-orient/staging/devapi.pearl-of-orient/node_modules/mongoose/lib/schematype.js:1210:14)
        at /home/pearl-of-orient/staging/devapi.pearl-of-orient/node_modules/mongoose/lib/document.js:2704:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      properties: {
        validator: [Function (anonymous)],
        message: 'Path `mangopayCardId` is required.',
        type: 'required',
        path: 'mangopayCardId',
        value: undefined
      },
      kind: 'required',
      path: 'mangopayCardId',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'Card validation failed'
}
```

**The request takes more than a minute and it returns a body null. I am using a sandbox account. My API in staging is in https.**

**Comment by fredericdelordm** [comment]
Hello @dhulqarnayn, do you still have the issue ?
