### ISSUE TITLE
TypeError: this._servicesLoader is not a function

### ISSUE THREAD

**Issue by scleriot** [Mangopay/mangopay2-nodejs-sdk#33]
Hi,

When I try importing the Node.js sdk by doing 
```
var mangopay = require('mangopay2-nodejs-sdk')({
    clientId: 'clientid',
    clientPassword: 'clientpassword',
    // Set the right production API url. If testing, omit the property since it defaults to sandbox URL
    //baseUrl: 'https://api.mangopay.com'
});
```

I get the following error : 
```
/application/node_modules/mangopay2-nodejs-sdk/lib/api.js:60
    this._servicesLoader();
         ^

TypeError: this._servicesLoader is not a function
    at Api (/application/node_modules/mangopay2-nodejs-sdk/lib/api.js:60:10)
    at Object.<anonymous> (/application/controllers/admin/freelancers.js:7:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /application/index.js:237:29
    at Array.forEach (native)
    at /application/index.js:235:49
    at Array.forEach (native)
    at Object.<anonymous> (/application/index.js:230:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/application/server.js:2:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

Node version : 6.8.1
SDK version : 1.3.0

**Comment by gabriellupu** [comment]
Hello!
What about trying:

```
var mangopay = require('mangopay2-nodejs-sdk');

var api = new mangopay({
    clientId: 'clientid',
    clientPassword: 'clientpassword',
    // Set the right production API url. If testing, omit the property since it defaults to sandbox URL
    //baseUrl: 'https://api.mangopay.com'
});
```
let me know how it goes.

**Comment by scleriot** [comment]
I thought I already tried this one, but apparently not because your version is working, thanks !
