### ISSUE TITLE
UnhandledPromiseRejection when timeout occurs

### ISSUE THREAD

**Issue by sicotdev** [Mangopay/mangopay2-nodejs-sdk#400]
When a timeout occurs, the sdk throws this error without any possibility to catch it.

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Cannot read properties of undefined (reading 'data')",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Cannot read properties of undefined (reading 'data')",
        "stack": [
            "TypeError: Cannot read properties of undefined (reading 'data')",
            "    at /var/task/node_modules/mangopay2-nodejs-sdk/lib/api.js:209:96",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at runNextTicks (node:internal/process/task_queues:65:3)",
            "    at listOnTimeout (node:internal/timers:528:9)",
            "    at processTimers (node:internal/timers:502:7)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Cannot read properties of undefined (reading 'data')",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)",
        "    at process.emit (node:events:513:28)",
        "    at emit (node:internal/process/promises:140:20)",
        "    at processPromiseRejections (node:internal/process/promises:274:27)",
        "    at processTicksAndRejections (node:internal/process/task_queues:97:32)",
        "    at runNextTicks (node:internal/process/task_queues:65:3)",
        "    at listOnTimeout (node:internal/timers:528:9)",
        "    at processTimers (node:internal/timers:502:7)"
    ]
}
```

Expected result: the sdk should call `reject` in case of a timeout, so the error can be caught and handled properly.

**Comment by fredericdelordm** [comment]
Hello @sicotdev, we are looking into it
